### PR TITLE
Install header files hierarchy

### PR DESCRIPTION
**Pull request by valnoel**
Keep headers hierarchy at install to fix includes

### CODE REVIEW

**Comment by tomjnixon** [comment]
Thanks for the PR. You definitely found a bug, but the fix isn't quite right as some of the headers in `include/` are not supposed to be public.

I'd like to fix this by moving the non-public headers to `src/`; I'll update this PR with that once it's done so you can check it out.

**Comment by tomjnixon** [comment]
Sorry for the delay, please have a look at #11.

**Comment by valnoel** [comment]
Hi @tomjnixon ! Thanks for your update, your changes look good to me and don't impact my usage of libear. :+1:

**Comment by valnoel** [comment]
Deprecated since #11

**Comment by tomjnixon** [comment]
great, thank you for your contribution

**Pull request closed without merging**
